"""Deterministic fictional client/account ownership shared by both notebook datasets.

Company labels are simulation labels, not real accounts or customer records.
No files are written and no random transaction data is generated by this module.
"""

COUNTRY_CITIES = {
    "US": ("AUSTIN", "SEATTLE", "DENVER"), "GB": ("BRISTOL", "LEEDS", "MANCHESTER"),
    "DE": ("HAMBURG", "MUNICH", "BONN"), "FR": ("LYON", "NANTES", "TOULOUSE"),
    "CA": ("TORONTO", "OTTAWA", "CALGARY"), "AU": ("SYDNEY", "PERTH", "ADELAIDE"),
    "SG": ("SINGAPORE",), "NL": ("UTRECHT", "ROTTERDAM"), "CH": ("ZURICH", "GENEVA"),
    "SE": ("STOCKHOLM", "MALMO"), "NZ": ("AUCKLAND", "WELLINGTON"),
    "IN": ("MUMBAI", "PUNE", "CHENNAI"), "MX": ("MONTERREY", "GUADALAJARA"),
    "BR": ("RECIFE", "CURITIBA", "SAO PAULO"), "JP": ("OSAKA", "NAGOYA"),
}

# Stable entity numbers must not be reassigned when extending this registry.
# Each client has one canonical name and a disjoint set of 3, 5, or 7 accounts.
FOCAL_CLIENTS = (
    (1, "PAYPAL", "fintech", "US", 7),
    (2, "VENMO", "fintech", "US", 3),
    (3, "PAYONEER", "fintech", "US", 5),
    (4, "TTT MoneyCorp", "fintech", "GB", 7),
    (5, "WISE", "fintech", "GB", 5),
    (6, "STRIPE", "fintech", "US", 3),
    (7, "AURORA GLOBAL TRADING LTD", "business", "GB", 3),
    (8, "CEDAR LOGISTICS GROUP", "business", "US", 5),
    (9, "QUARTZ IMPORT EXPORT LTD", "business", "SG", 7),
)
FINTECH_NAMES = tuple(name for _, name, kind, _, _ in FOCAL_CLIENTS if kind == "fintech")


def build_registry():
    """Return fixed clients, account ownership, and country/type selection pools."""
    clients, owners, pools = {}, {}, {}

    def add(number, name, kind, country, count, focal=False):
        entity_id = f"{number:032x}"
        accounts = tuple(f"01{number:08d}{slot:04d}" for slot in range(1, count + 1))
        city = COUNTRY_CITIES[country][number % len(COUNTRY_CITIES[country])]
        client = dict(name=name, entity_id=entity_id, accounts=accounts, kind=kind,
                      country=country, city=city, focal=focal, number=number)
        if name in clients or any(account in owners for account in accounts):
            raise ValueError("Client names and account ownership must be unique")
        clients[name] = client
        for account in accounts:
            owners[account] = client
        pools.setdefault((country, kind), []).append(client)

    for number, name, kind, country, count in FOCAL_CLIENTS:
        add(number, name, kind, country, count, focal=True)

    first_names = ("SAN", "MEI", "ELARA", "TAVIN", "NERIN", "ALORA", "DEVAN", "MIREL", "SOREN", "LYRA", "ARUN", "LINA")
    last_names = ("ZHANG", "CHEN", "ASTER", "QUILL", "VALE", "SOLEN", "ROWAN", "FEN", "ORIN", "LARK", "RAO", "PATEL", "KATO", "MORENO", "SILVA")
    brands = ("AURORA", "COBALT", "QUARTZ", "CEDAR", "LUNAR", "EMBER", "NOVA", "ORBIT", "MAPLE", "WILLOW", "HARBOR", "SUMMIT")
    sectors = ("MARKET", "LOGISTICS", "DIGITAL", "RETAIL", "EXPORTS", "SERVICES")
    for country_index, country in enumerate(COUNTRY_CITIES):
        city = COUNTRY_CITIES[country][0]
        for i, first in enumerate(first_names):
            add(1000 + country_index * 100 + i, f"{first} {last_names[country_index]}",
                "person", country, (3, 5, 7)[i % 3])
        for i, brand in enumerate(brands):
            add(10000 + country_index * 100 + i, f"{brand} {city} {sectors[i % len(sectors)]} LTD",
                "business", country, (3, 5, 7)[i % 3])
        for i, brand in enumerate(brands[:3]):
            add(20000 + country_index * 100 + i, f"{brand} {city} BANK",
                "bank", country, (3, 5, 7)[i])
    return clients, owners, pools


def choose_pair(rng, sequence, product, clients, pools):
    """Exactly one fintech leg every fourth row; all other core legs are ordinary clients."""
    countries = tuple(COUNTRY_CITIES)

    def ordinary(country):
        return rng.choice(pools[country, rng.choice(("person", "business"))])

    def counterparty_country(country):
        if product == "Domestic ACH":
            return country
        if product == "International ACH":
            return rng.choice([c for c in countries if c != country])
        return country if rng.random() < 0.6 else rng.choice(countries)

    if (sequence - 1) % 4 == 0:
        focal = clients[rng.choice(FINTECH_NAMES)]
        other = ordinary(counterparty_country(focal["country"]))
        return (focal, other) if ((sequence - 1) // 4) % 2 == 0 else (other, focal)
    originator = ordinary(rng.choice(countries))
    beneficiary = ordinary(counterparty_country(originator["country"]))
    # Avoid selecting the same client on both legs of an ordinary transaction.
    while beneficiary["entity_id"] == originator["entity_id"]:
        beneficiary = ordinary(beneficiary["country"])
    return originator, beneficiary


def party_fields(client, account):
    """The 14 existing wide-schema fields, with role-independent identity."""
    if account not in client["accounts"]:
        raise ValueError("Account does not belong to the selected client")
    bank = client["kind"] == "bank"
    return [client["entity_id"], "2" if client["focal"] else "1", "2" if bank else "1",
            account, account, client["name"], client["name"], client["name"],
            f'SYNADDR{client["number"]:012d}', client["country"], client["city"],
            "1" if client["focal"] else "0", "1", "1" if bank else "0"]
